[package]
name = "dndex"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20.0", features = ["csr"] }
stylist = { version = "0.12.0", features = ["yew_integration", "parser"] }
wasm-bindgen = "0.2.87"
