[workspace]
members = [
    "frontend",
    # "backend",
]

# linker error mitigation
# issue being worked on here: https://github.com/futursolo/stylist-rs/pull/123
[profile.dev.package.wasm-bindgen]
debug-assertions = false
