version: '3'
services:
  api:
    image: 'eepmoody/open5e-api:staging'
    hostname: open5e-api
    container_name: open5e-api
    ports:
      - '8888:8888'
    entrypoint: [
      "/bin/sh", "-c",
      "SECRET_KEY=${SECRET_KEY} pipenv run gunicorn -b :8888 -w `python -c 'import os; print(os.cpu_count() * 2)'` --threads `python -c 'import os; print(os.cpu_count())'` server.wsgi:application"
    ]
  database:
    image: 'surrealdb/surrealdb:latest'
    hostname: surrealdb
    container_name: surrealdb
    command: "start -b 0.0.0.0:9999 -u ${DB_USER} -p ${DB_PASS}"
    ports:
      - '9999:9999'
  import:
    image: 'surrealdb/surrealdb:latest'
    container_name: surrealdb-import
    volumes:
      - ./data:/data
    depends_on:
      - database
    restart: "no"
    command: "import -c http://surrealdb:9999 -u ${DB_USER} -p ${DB_PASS} --ns dndex --db dndex /data/import.surql"
