version: '3'
services:
  server:
    image: 'eepmoody/open5e-api:staging'
    build: .
    environment:
      - OPEN5E_DEBUG=false
      - SERVER_NAME=dndex
      - SECRET_KEY=secret
    ports:
      - '8888:8888'
    volumes:
      - .:/usr/src/open5e-api/
    depends_on:
      - watchtower
  watchtower:
    image: v2tec/watchtower
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: '--interval 600 --cleanup'
